[features]
seeds = false
[programs.localnet]
casino = "4A74C5CvTQwwUQDYJrKzMwXNywJwi5qoUuvpYgJLaYY2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/mbenz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
