name: "Setup Solana"
description: "Setup Solana"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      name: Cache Solana Tool Suite
      id: cache-solana
      with:
        path: |
          ~/.cache/solana/
          ~/.local/share/solana/
        key: solana-${{ runner.os }}-v0000-${{ env.SOLANA_CLI_VERSION }}
    # - name: Check if Solana exists
    #   id: check-solana-avail
    #   run: solana --version
    #   shell: bash
    - run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_CLI_VERSION }}/install)"
      shell: bash
      # if: steps.check-solana-avail.outputs.status == 'failure'
    - run: echo "$HOME/.local/share/solana/install/active_release/bin/" >> $GITHUB_PATH
      shell: bash
    - run: solana-keygen new --no-bip39-passphrase --force
      shell: bash
      # if: steps.check-solana-avail.outputs.status == 'failure'
    - run: solana config set --url localhost
      shell: bash
      # if: steps.check-solana-avail.outputs.status == 'failure'
