name: Continuous Integration NPM

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
    branches:
      - develop
      - staging

env:
  working_dir: ./ts-client

jobs:
  changed_files:
    runs-on: ubuntu-latest
    outputs:
      program: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            ts-client

  ts-test:
    needs: changed_files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - name: Install dependencies
        working-directory: ${{ env.working_dir }}
        run: pnpm install
      - name: Run tests
        working-directory: ${{ env.working_dir }}
        run: pnpm run test