[programs.localnet]
mint_nft = "7NpT6MAcQXSAVWvAAxMHLrouHhjX93JXg1xHAtJHAbhm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/leonnguyen/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
